---

- name: Initialize 
  gather_facts: false
  become: yes
  hosts: k8s-master
  tasks:
    - name: Initialize cluster
      command: kubeadm init
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    - name: Setup kubeconfig for ubuntu user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/ubuntu/.kube
        - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        - chown ubuntu:ubuntu /home/ubuntu/.kube/config
    - name: Copy CNI plugin bash script to server location
      copy: src=weavenet.sh dest=/tmp/cni.sh mode=0777
    - name: Install cni plugin
      command: sh /tmp/cni.sh